### ISSUE TITLE
Issues with running pod install

### ISSUE THREAD

**Issue by whitecow** [opentok/accelerator-annotation-ios#5]
2 issues/questions

1. pod 'OTAnnotationKit'
I added it here is that correct?
def shared_pods
    pod 'LHToolbar', '= 1.3.0-beta'
    pod 'OTAcceleratorCore’, '= 1.1.5'
    pod 'OTAnnotationKit'
end

2. When running "pod install" i receive the following error.

[!] Error installing OTAcceleratorPackUtil
[!] /usr/local/bin/git clone https://github.com/opentok/acc-pack-common.git /var/folders/yf/wb3w6d0900j6qn8qhgfhqc640000gn/T/d20190125-64413-1buoq3t --template= --single-branch --depth 1 --branch 2.0.8

Cloning into '/var/folders/yf/wb3w6d0900j6qn8qhgfhqc640000gn/T/d20190125-64413-1buoq3t'...
remote: Repository not found.
fatal: repository 'https://github.com/opentok/acc-pack-common.git/' not found

**Comment by abdulajet** [comment]
Hey, @whitecow OTAnnotationKit was removed from the project. Your issue should be resolved now.
